readme: README.md
author: Graham\ Chance
github_url: https://github.com/gtchance/firebaseswift
module: FirebaseSwift
exclude:
  - Tests/*
  - Dependencies/*
xcodebuild_arguments:
    - "-project"
    - "FirebaseSwift.xcodeproj"
    - "-scheme"
    - "FirebaseSwift"